# Generated by Django 4.0.3 on 2022-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(db_index=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
